### ISSUE TITLE
Error when world loaded

### ISSUE THREAD

**Issue by YasonCore** [owmii/Enemyz#1]
Crash-report:
 ---- Minecraft Crash Report ----
// My bad.

Time: 15.08.19 18:03
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.LivingEntity.getEntityWorld()Lnet/minecraft/world/World;
	at xieao.enemyz.Handler.setAndSyncTarget(Handler.java:45) ~[?:0.2.2] {}
	at net.minecraftforge.eventbus.ASMEventHandler_82_Handler_setAndSyncTarget_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:307) ~[?:?] {}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1955) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70071_h_(BaseCreatureEntity.java:1336) ~[?:1.0] {}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {}
	at net.minecraft.world.server.ServerWorld$$Lambda$5977/713924732.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at xieao.enemyz.Handler.setAndSyncTarget(Handler.java:45)
	at net.minecraftforge.eventbus.ASMEventHandler_82_Handler_setAndSyncTarget_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:307)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1955)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397)
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70071_h_(BaseCreatureEntity.java:1336)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
	at net.minecraft.world.server.ServerWorld$$Lambda$5977/713924732.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: lycanitesmobs:yeti (com.lycanitesmobs.core.entity.creature.EntityYeti)
	Entity ID: 4
	Entity Name: Yeti 
	Entity's Exact location: -135.44, 70.00, 101.47
	Entity's Block location: World: (-136,70,101), Chunk: (at 8,4,5 in -9,6; contains blocks -144,0,96 to -129,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.01, -0.08, -0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Новый миркпеа
	Level seed: 5639352087181436805
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-192,63,96), Chunk: (at 0,3,0 in -12,6; contains blocks -192,0,96 to -177,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1095 game time, 1095 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 165794 (now: false), thunder time: 146338 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5753307624 bytes (5486 MB) / 8220835840 bytes (7840 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.46.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.46.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.46.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.46.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4_pre2_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.46.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.46
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		betteranimals-1.14.4-5.2.1.jar Cyber's Better Animal Models {betteranimals@5.2.1 DONE}
		betteranimalsplus-1.14.4-7.0.2.1.jar Better Animals Plus {betteranimalsplus@7.0.2.1 DONE}
		BiomesOPlenty-1.14.4-9.0.0.231-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.229 DONE}
		burningtorch-2.1.1.jar Burning Torch {burningtorch@2.1.1 DONE}
		camera-1.4.2.jar Camera Mod {camera@1.4.2 DONE}
		DoggyTalents-1.14.4-1.15.1.3-universal.jar Doggy Talents {doggytalents@1.15.1.3 DONE}
		DungeonCrawl-1.14.4-1.3.0.jar Dungeon Crawl {dungeoncrawl@1.3.0 DONE}
		enchxchg-1.14.4-4.0.5.jar Enchantments Exchanger {enchxchg@1.14.4-4.0.5 DONE}
		Enemyz-1.14.4-0.2.2.jar Enemyz {enemyz@0.2.2 DONE}
		EquipmentTooltips-1.14.4-1.3.2+10.jar Equipment Tooltips {equipmenttooltips@1.3.2+10 DONE}
		exp_bottling-1.14.4-2.jar EXP Bottling {exp_bottling@1.14.4-2 DONE}
		extlights-1.0.jar Extended Lights {extlights@1.0 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		flying_things-1.8.4-1.14.4.jar The Flying Things {flying_things@1.8.4 DONE}
		forbidden_arcanus-1.14.4-1.0-Beta-3.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.0-Beta-3 DONE}
		FpsReducer-mc1.14.4-1.12.5.jar FPS Reducer {fpsreducer@mc1.14.4-1.12.5 DONE}
		globaldatapack-1.14.4-1.1.jar Dark Roleplay - Global Datapacks {drpglobaldatapack@1.14.4-1.1 DONE}
		guardillagers-1.14.4-1.0.1.jar GuardIllagers {guardillagers@1.0.1 DONE}
		hunterillager-1.14.4-0.1.2.jar HunterIllager {hunterillager@0.1.2 DONE}
		lycanitesmobs-1.14.4-2.1.0.0-beta16.jar Lycanites Mobs {lycanitesmobs@1.0 DONE}
		MobRebirth-1.14.4-8.0.1.jar Mob Rebirth {mobrebirth@8.0.1 DONE}
		Morpheus-1.14.4-4.2.24.jar Morpheus {morpheus@version DONE}
		openbackup-1.14.4-0.0.1.3.jar OpenBackup {openbackup@1.14.4-0.0.1.2 DONE}
		Ping-1.14.4-1.6.3.jar Ping {ping@1.14.4-1.6.3 DONE}
		ProgressiveBosses-2.1.1.jar Progressive Bosses {progressivebosses@2.1.1 DONE}
		randompatches-1.14.4-1.18.1.1.jar RandomPatches {randompatches@1.14.4-1.18.1.1 DONE}
		rsgauges-1.14.4-1.1.7-b2.jar Redstone Gauges and Switches {rsgauges@1.1.7-b2 DONE}
		ServerTabInfo-1.14.4-1.2.5-b2.jar Server Tab Info {servertabinfo@1.2.5-b2 DONE}
		SignButton-1.14.2-2.0.1.jar Sign Button {signbutton@version DONE}
		SilentGear-1.14.4-1.3.8+56.jar Silent Gear {silentgear@1.3.8+56 DONE}
		SilentGems-1.14.4-3.3.6+63.jar Silent's Gems 3 {silentgems@3.3.6+63 DONE}
		SilentLib-1.14.4-4.3.1+39.jar Silent Lib {silentlib@4.3.1+39 DONE}
		simplefarming-1.14.4-1.0.8.jar Simple Farming {simplefarming@1.14.4-1.0.8 DONE}
		simplylight-0.8.6.jar Simply Light {simplylight@0.8.6 DONE}
		SnowRealMagic-1.14.4-1.0.1.jar Snow! Real Magic! {snowrealmagic@1.0.1 DONE}
		Kiwi-1.14.4-2.3.1.jar Kiwi {kiwi@2.3.1 DONE}
		speedyladders-1.14.4-1.0.2.jar Speedy Ladders {speedyladders@1.14.4-1.0.2 DONE}
		StuffASockInIt-1.14.4-3.0.3.jar StuffASockInIt {sasit@3.0.3 DONE}
		themidnight-0.4.jar The Midnight {midnight@0.4 DONE}
		tombstone-3.7.5-1.14.4.jar Corail Tombstone {tombstone@3.7.5 DONE}
		ToolBelt-1.14.4-1.11.0.jar Tool Belt {toolbelt@1.11.0 DONE}
		TreasureBags-1.14.4-1.1.1+18.jar Treasure Bags {treasurebags@1.1.1+18 DONE}
		Upgrade+Aquatic+Wave+Three+v4+-+Beta+v1.0.6.jar Upgrade Aquatic {upgrade_aquatic@1.0.6 DONE}
		Xaeros_Minimap_1.17.6_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.17.6 DONE}
		XaerosWorldMap_1.4.7.1_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.7 DONE}
		forge-1.14.4-28.0.46-universal.jar Forge {forge@28.0.46 DONE}
		goprone-1.14.x-1.0.3.jar GoProne {goprone@1.14.x-1.0.3 DONE}
		forge-1.14.4-28.0.46-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 0 / 8; []
	Data Packs: mod:enemyz, vanilla, modpack:larger phantoms v1.0.0.zip, modpack:VanillaTweaks_c223325.zip (incompatible), modpack:Tridents_o_Plenty_1.1.zip (incompatible), modpack:Nether_Creepers_1.0.zip (incompatible), modpack:Deep_Mobs_1.0.zip (incompatible), modpack:Chest_Loot_Upgrade.zip (incompatible), mod:xaeroworldmap, mod:xaerominimap, mod:upgrade_aquatic, mod:treasurebags, mod:toolbelt, mod:tombstone, mod:speedyladders, mod:snowrealmagic, mod:simplylight, mod:simplefarming, mod:silentlib, mod:silentgems, mod:silentgear, mod:signbutton, mod:servertabinfo, mod:sasit, mod:rsgauges, mod:randompatches, mod:progressivebosses, mod:ping, mod:openbackup, mod:morpheus, mod:mobrebirth, mod:midnight, mod:lycanitesmobs, mod:kiwi, mod:hunterillager, mod:guardillagers, mod:goprone, mod:fpsreducer, mod:forge, mod:forbidden_arcanus, mod:flying_things, mod:fastleafdecay, mod:extlights, mod:exp_bottling, mod:equipmenttooltips, mod:enchxchg, mod:dungeoncrawl, mod:drpglobaldatapack, mod:doggytalents, mod:camera, mod:burningtorch (incompatible), mod:biomesoplenty, mod:betteranimalsplus, mod:betteranimals, mod:attributefix, mod:appleskin
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

[latest.log](https://github.com/xieaoDev/Enemyz/files/3505672/latest.log)

**Comment by owmii** [comment]
Thank you!, i fixed the crash caused by mapping due to buildscript changes in forge 28.0.46.
